jobs:
  include:
    - os: osx
#       osx_image: xcode10.1
#     - os: osx
#       osx_image: xcode12.5
#     - os: osx
#       osx_image: xcode13.1
#     - os: osx
#       osx_image: xcode12.4
#     - os: osx
#       osx_image: xcode12.5
#     - os: osx
#       osx_image: xcode12.5.1
      


language: bash

before_script:
    - sw_vers
#     - wget https://letsencrypt.org/certs/isrgrootx1.der
#     - sudo security import isrgrootx1.der -k ~/Library/Keychains/login.keychain
#     - sudo security import isrgrootx1.der -k /Library/Keychains/System.keychain
#     - wget https://letsencrypt.org/certs/isrgrootx1.pem
#     - sudo security -v add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain isrgrootx1.pem
#     - wget https://letsencrypt.org/certs/isrgrootx1.der
#     - ls -lah /Library/Keychains
#     - sudo security import isrgrootx1.der -k /Library/Keychains/System.keychain
#     - sudo security import isrgrootx1.der -k /System/Library/Keychains/SystemRootCertificates.keychain
#     - sudo security add-trusted-cert -d -r trustRoot -k /System/Library/Keychains/SystemRootCertificates.keychain isrgrootx1.der
#     - curl -o- -L https://yarnpkg.com/install.sh | bash
#     - yarn add react
    - wget https://letsencrypt.org/certs/isrgrootx1.der
    - wget https://letsencrypt.org/certs/isrg-root-x2.der
    - wget https://letsencrypt.org/certs/lets-encrypt-r3.der
    - sudo security import isrgrootx1.der -k "/Library/Keychains/System.keychain"
    - sudo security import isrg-root-x2.der -k "/Library/Keychains/System.keychain"
    - sudo security import lets-encrypt-r3.der -k "/Library/Keychains/System.keychain"
    - sudo security -v add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" isrgrootx1.der
    - sudo security -v add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" isrg-root-x2.der
    - sudo security -v add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" lets-encrypt-r3.der
    - export HOMEBREW_NO_AUTO_UPDATE=1
    - brew install curl
    - curl -o- -L https://yarnpkg.com/install.sh | bash
#     - openssl version -a
#     - curl -v https://rubies.travis-ci.org/osx/10.15/x86_64/ruby-2.4.1.tar.bz2
#     - brew install openssl
#     - openssl version -a
#     - curl -v https://rubies.travis-ci.org/osx/10.15/x86_64/ruby-2.4.1.tar.bz2
#     - df -h
#     - xcversion simulators
#     - xcodebuild -version
#     - xcodebuild -showsdks
#     - ruby --version
#     - java -Xmx32m -version
#     - xcrun simctl list
#     - ls -al /Library/Developer/CommandLineTools/SDKs
#     - rvm --version
#     - pod --version
#     - diskutil info -all
#     - gem which cocoapods
#     - fastlane -v
#     - carthage version
#     - xcrun --sdk macosx --show-sdk-path
#     - brew --version
#     - echo $HOMEBREW_NO_INSTALL_CLEANUP
#     - pip install flake8
#     - pip3 install flake8
#     - python --version
#     - python2 --version
#     - python3 --version
#     - ls -lah /Applications/


