matrix:
  include:
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11

language: bash

addons:
  homebrew:
    packages:
    - htop
    
before_script:
    - sw_vers
    - xcodebuild -version
    - xcodebuild -showsdks
    - ruby --version
    - java -version
    - xcrun simctl list
    - rvm --version
    - pod --version
    - gem which cocoapods
    - fastlane -v
    - carthage version
    - xcrun --sdk macosx --show-sdk-path
    - brew --version
    - echo $HOMEBREW_NO_INSTALL_CLEANUP


