matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.4

language: bash

    
before_script:
    - sw_vers
    - xcodebuild -version
    - xcodebuild -showsdks
    - ruby --version
    - java -version
    - xcrun simctl list
    - rvm --version
    - pod --version
    - diskutil info -all
    - gem which cocoapods
    - fastlane -v
    - carthage version
    - xcrun --sdk macosx --show-sdk-path
    - brew --version
    - echo $HOMEBREW_NO_INSTALL_CLEANUP
    - pip install flake8
    - pip3 install flake8
    - python --version
    - python2 --version
    - python3 --version
    - ls -lah /Applications/


