os: osx

language: bash

before_script:
    - sw_vers
    - xcodebuild -version
    - xcodebuild -showsdks
    - ruby --version
    - java -version
    - xcrun simctl list
    - rvm --version
    - pod --version
    - gem which cocoapods
    - fastlane -v
    - carthage version
