matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      
    - os: osx
      osx_image: xcode9.4.1

    - os: osx
      osx_image: xcode11.1   
      
    - os: osx
      osx_image: xcode11.2.1
            
language: bash

before_script:
    - sw_vers
    - xcodebuild -version
    - xcodebuild -showsdks
    - ruby --version
    - java -version
    - xcrun simctl list
    - rvm --version
    - pod --version
    - gem which cocoapods
    - fastlane -v
    - carthage version
