jobs:
  include:
    - os: osx
      osx_image: xcode12.3

language: bash

before_script:
    - sw_vers
    - df -h
    - xcodebuild -version
    - rvm --version
    - echo $rvm_path
    - cat $rvm_path/user/db
    - rvm use 2.7.0 --install --binary --fuzzy --debug
    
    
    
    
