jobs:
  include:
    - os: osx
      osx_image: xcode-cs
    - os: osx
      osx_image: xcode13.4 
    - os: osx
      osx_image: xcode13.3
    - os: osx
      osx_image: xcode13.2
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode12.5

before_script:
    - sw_vers
    - df -h
    - xcodebuild -version
    - rvm --version
    - echo $rvm_path
    - cat $rvm_path/user/db

script:
#   - rvm install 3.0.0
  - rvm get head
  - rvm --version
  - rvm use 3.0.0 --install --binary --fuzzy
#   - rvm use 3.0.0
  - ruby --version
  - gem install rake
  
    
    
    
    
