os: osx
osx_image: xcode-cs
  

before_script:
  - sw_vers
  - uname -a
  - rvm --version
    
script:
#   - rvm install 3.0.0
  - rvm get head
  - rvm --version
  - rvm use 3.0.0 --install --binary --fuzzy
#   - rvm use 3.0.0
  - ruby --version 
  
  
