jobs:
  include:
    - os: osx
      osx_image: xcode12
    - os: osx
      osx_image: xcode15

language: bash

before_script:
    - sw_vers
    - df -h
    - xcodebuild -version
    - xcodebuild -showsdks
    - ruby --version
    - java -version
    - xcrun simctl list
    - rvm --version
    - pod --version
    - diskutil info -all
    - gem which cocoapods
    - fastlane -v
    - carthage version
    - xcrun --sdk macosx --show-sdk-path
    - brew --version
    - echo $HOMEBREW_NO_INSTALL_CLEANUP
    - pip install flake8
    - pip3 install flake8
    - python --version
    - python2 --version
    - python3 --version
    - ls -lah /Applications/


