arch: ppc64le
dist: bionic

services:
  - postgresql

script:
  - psql -c 'create database name;' -U travis;
  - psql -c 'create database email;' -U postgres;
  - sudo psql -c 'create database login;' -U postgres;
