jobs:
  include:
    - os: osx
      osx_image: xcode15
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3beta
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.3
    - os: osx    
      osx_image: xcode11.4
    - os: osx
      osx_image: xcode11.5
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode11.7
    - os: osx
      osx_image: xcode12u

language: bash

before_script:
    - sw_vers
    - df -h
    - xcodebuild -version
